# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cascade < Formula
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"
  version "0.1.35"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.35/cascade_Darwin_x86_64.tar.gz"
      sha256 "ed0e278e78f0d7ee04e6dd496b6f2e674a0faf81e1d663462a003fe405b8058d"

      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.35/cascade_Darwin_arm64.tar.gz"
      sha256 "6ce7a530748bb4ae66b4f22eeb307046a4342257456cb92a1194ae19bc837cf3"

      def install
        bin.install "cascade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.35/cascade_Linux_x86_64.tar.gz"
      sha256 "5ded0b342d35e66abbc709d48f306562428d3e1548807aea80de717601e6bac0"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.35/cascade_Linux_armv6.tar.gz"
      sha256 "db30105ab00b9c24761dcc703cac77fdbeb47651f3cfd9efe56ee28ba9f89b8b"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.35/cascade_Linux_arm64.tar.gz"
      sha256 "a34597e968ad6aebe3685d3b7a0d61e0c66595724783c4ebdfeac969926509cc"
      def install
        bin.install "cascade"
      end
    end
  end

  test do
    system "#{bin}/cascade -version"
  end
end
