# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cascade < Formula
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"
  version "0.1.36"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.36/cascade_Darwin_x86_64.tar.gz"
      sha256 "d59589ff638cf395a59e552c6a1456bd2f5d672b6d39a009a46cb4c56db6232e"

      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.36/cascade_Darwin_arm64.tar.gz"
      sha256 "a9ecaecd9472e7e91a33a4e3006a2cee5b2a06191e267a2e6bdd50b5e630a7b6"

      def install
        bin.install "cascade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.36/cascade_Linux_x86_64.tar.gz"
      sha256 "c309c1dcf6b1c5816102736fbfb395df4ecd36eb3a38baca429e9e1238cbf482"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.36/cascade_Linux_armv6.tar.gz"
      sha256 "ffec29436244a811be4b682dc2baaca42f6712cd866bdb21581f788de20be49f"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.36/cascade_Linux_arm64.tar.gz"
      sha256 "36dc1f1d68f02279e1b95d374884516ac2604c5ef2c69b97e1ae4c5048c1df68"
      def install
        bin.install "cascade"
      end
    end
  end

  test do
    system "#{bin}/cascade -version"
  end
end
