# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envset < Formula
  desc "run commands in an environment defined using a ini configuration file."
  homepage "https://github.com/goliatone/go-envset"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/go-envset/releases/download/v0.6.2/envset_0.6.2_darwin_arm64.tar.gz"
      sha256 "515348ce3300076d4dd1ef79368a22d086eb774dc8e957498c948fedfc87df59"

      def install
        bin.install "envset"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/go-envset/releases/download/v0.6.2/envset_0.6.2_darwin_x86_64.tar.gz"
      sha256 "74b5ba3740f9a6e3aa08ce4e479a6203aa41321de1c6d3a77e01d90f64b0b9a6"

      def install
        bin.install "envset"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/go-envset/releases/download/v0.6.2/envset_0.6.2_linux_armv6.tar.gz"
      sha256 "829abf6aa0dd82b5178acafb7912f9441c377ba061170a8f2a6f4c3fd76cfccc"

      def install
        bin.install "envset"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/go-envset/releases/download/v0.6.2/envset_0.6.2_linux_arm64.tar.gz"
      sha256 "eaee6346570f32384f0552cd9c626dbbc52860fb6db4cea607e3eb1af93d4d43"

      def install
        bin.install "envset"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/go-envset/releases/download/v0.6.2/envset_0.6.2_linux_x86_64.tar.gz"
      sha256 "787416e70ed8b1c18f13750e32539bfe3746db56a6940ddbf0d9c8b91d6d0186"

      def install
        bin.install "envset"
      end
    end
  end

  test do
    system "#{bin}/envset -V"
  end
end
