# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashid < Formula
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"
  version "0.0.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/goliatone/hashid/releases/download/v0.0.6/hashid_Darwin_x86_64.tar.gz"
      sha256 "90fa279bb7ca915b8a3a3c12957fc11e83e2c7bee65284778fb8fd58648de91b"

      def install
        bin.install "hashid"
      end
    end
    on_arm do
      url "https://github.com/goliatone/hashid/releases/download/v0.0.6/hashid_Darwin_arm64.tar.gz"
      sha256 "4ad6c1e8043c8f37ed087dee3680e3bf70e933763120c856a34816235c7991bf"

      def install
        bin.install "hashid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.6/hashid_Linux_x86_64.tar.gz"
        sha256 "104437f346bd86c46ed95e817811b629ac809ae95828031e78d17d61299e8b83"

        def install
          bin.install "hashid"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.6/hashid_Linux_armv6.tar.gz"
        sha256 "2308bf641ed5aa75cfeb4b39c36c53e21767db0e3777441c4e82517e2d895d0b"

        def install
          bin.install "hashid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.6/hashid_Linux_arm64.tar.gz"
        sha256 "68d20b4072247a091d5a12db06d18f97cdde2afce67eb036acf7bfb925eba8cd"

        def install
          bin.install "hashid"
        end
      end
    end
  end

  test do
    system "#{bin}/hashid -version"
  end
end
