# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashid < Formula
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/hashid/releases/download/v0.1.1/hashid_Darwin_x86_64.tar.gz"
      sha256 "9fcada9fa12d3efa44a230d501190ec94dfac902f836125241acf3f68630120a"

      def install
        bin.install "hashid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/hashid/releases/download/v0.1.1/hashid_Darwin_arm64.tar.gz"
      sha256 "9f847e4342315d4e1b93545e39ae5e19670cae4ba20ab441725af0b9d4998a90"

      def install
        bin.install "hashid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.1.1/hashid_Linux_x86_64.tar.gz"
        sha256 "ce5858b955a4bba7323bfb6ed3d104cfea3cd519093bb7f938d46752a1bdb52b"

        def install
          bin.install "hashid"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.1.1/hashid_Linux_armv6.tar.gz"
        sha256 "db888b64fbcd104175e5c751a99059c53b118a8081e3624cf804f3316c9cae46"

        def install
          bin.install "hashid"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.1.1/hashid_Linux_arm64.tar.gz"
        sha256 "008fe03dd42ca51979e0f498193662556820330cf5331c3a5e1c9cc3b2b6d173"

        def install
          bin.install "hashid"
        end
      end
    end
  end

  test do
    system "#{bin}/hashid -version"
  end
end
