# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashid < Formula
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"
  version "0.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/goliatone/hashid/releases/download/v0.0.5/hashid_Darwin_x86_64.tar.gz"
      sha256 "626f036851dee6c5bc4f46a2c7f376f917f83168ae814a653745afdc1523b636"

      def install
        bin.install "hashid"
      end
    end
    on_arm do
      url "https://github.com/goliatone/hashid/releases/download/v0.0.5/hashid_Darwin_arm64.tar.gz"
      sha256 "e200ee3120007c9768c2233e42dd4f658c73bdd9724e52fa1468c79fa7b99958"

      def install
        bin.install "hashid"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.5/hashid_Linux_x86_64.tar.gz"
        sha256 "567f194a262e11ead35fea466fbc2a3c4abb0b31036b32ae40497d3ecc575462"

        def install
          bin.install "hashid"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.5/hashid_Linux_armv6.tar.gz"
        sha256 "a24c8380aa298dca43fd5ea702dd4ccbc6a50d61eb86998028da25083966972c"

        def install
          bin.install "hashid"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/goliatone/hashid/releases/download/v0.0.5/hashid_Linux_arm64.tar.gz"
        sha256 "2fc5afa0e8f20ef5a055b2e36eed2d72509edf7068ea4e2f1e9650303e0f4661"

        def install
          bin.install "hashid"
        end
      end
    end
  end

  test do
    system "#{bin}/hashid -version"
  end
end
