# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgr < Formula
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.12/lgr_0.0.12_darwin_arm64.tar.gz"
      sha256 "1db14ab589e5082a0e226762dc54ab7117d389dac8f9070429300defdd9898e2"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.12/lgr_0.0.12_darwin_x86_64.tar.gz"
      sha256 "2be13bd9e0fb0b4ac85a3d430adfdef286586cb2f78a7351bd882a9ba6e9c800"

      def install
        bin.install "lgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.12/lgr_0.0.12_linux_x86_64.tar.gz"
      sha256 "cf4cb84578b20d563068a59c2a4c90a5bc737d7cbb12a8dac78c3d307521a031"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.12/lgr_0.0.12_linux_armv6.tar.gz"
      sha256 "031ddee43f001dba311039a451ee3c2c849105d9246d4b73b3fc179a8ecf7b77"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.12/lgr_0.0.12_linux_arm64.tar.gz"
      sha256 "1140bdb25b933b46d48f65493e82545c9b3342dbb1b345a1e0a9882acff1391a"

      def install
        bin.install "lgr"
      end
    end
  end

  test do
    system "#{bin}/lgr -V"
  end
end
