# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgr < Formula
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.4/lgr_0.0.4_darwin_x86_64.tar.gz"
      sha256 "0e10b2dff16c97676aae2d1d64a06a4aa5e4d41feec15b7d2ae830067285cdee"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.4/lgr_0.0.4_darwin_arm64.tar.gz"
      sha256 "87631db9c21f4b474415cdd6838d7b393f60bcf7ca36b73a74c69231b32aa896"

      def install
        bin.install "lgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.4/lgr_0.0.4_linux_x86_64.tar.gz"
      sha256 "faddccbaa0e82074e90ef1a038798319eb4896c62e815f1b3aac428d6170499f"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.4/lgr_0.0.4_linux_armv6.tar.gz"
      sha256 "950aed4b8dcd084fd9b0d1202fdacbc7e4d66fd79f9e93e7a66dd18597868de7"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.0.4/lgr_0.0.4_linux_arm64.tar.gz"
      sha256 "fc6e1922ef6a0d9398e17c0640e584bb78282e0e87dd695921c098bfc0fedd86"

      def install
        bin.install "lgr"
      end
    end
  end

  test do
    system "#{bin}/lgr -V"
  end
end
