# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgr < Formula
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.1/lgr_0.1.1_darwin_x86_64.tar.gz"
      sha256 "c454d95503436fa0c1ae9512e1b15ee1c6781bd9a0c261d7db912da2e63393e0"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.1/lgr_0.1.1_darwin_arm64.tar.gz"
      sha256 "4e707d6742fae0c988460df6cd3965b7e9860acdafd04193b6ae0eaf0cb7822f"

      def install
        bin.install "lgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.1/lgr_0.1.1_linux_arm64.tar.gz"
      sha256 "05ec803a600d8a65912a9fcd1799ddd816c7ba65e9895f0c0e9a183eadf42a7d"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.1/lgr_0.1.1_linux_armv6.tar.gz"
      sha256 "5f86ecd0cd89bc8bdeaf75c3d9223d30b9f821284ba27d6496e656fca9e2f23f"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.1/lgr_0.1.1_linux_x86_64.tar.gz"
      sha256 "b82892dbefed869d91a62b5823553f46ddf9f70f9d8b1b7020ad4cce08535791"

      def install
        bin.install "lgr"
      end
    end
  end

  test do
    system "#{bin}/lgr -V"
  end
end
