# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Switchd < Formula
  desc "local development CLI for DNS, Caddy, and tunnel workflows on macOS."
  homepage "https://github.com/goliatone/switchboard-hub"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/switchboard-hub/releases/download/v0.5.0/switchd_Darwin_x86_64.tar.gz"
      sha256 "999793e5cbbeca034e42448e01c99302047e2c0351d32aaab0bf31fe064633d4"

      define_method(:install) do
        bin.install "switchd"
        bin.install_symlink "switchd" => "sbd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/switchboard-hub/releases/download/v0.5.0/switchd_Darwin_arm64.tar.gz"
      sha256 "87d87a747e635c43db66c435f2b9993f7477de1d1e1022275da316fd3d418ca1"

      define_method(:install) do
        bin.install "switchd"
        bin.install_symlink "switchd" => "sbd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/switchboard-hub/releases/download/v0.5.0/switchd_Linux_x86_64.tar.gz"
      sha256 "d166d6c53c8e7e3e1734c3a6d318581eedd24c2a1831d384107c01436cc054ee"
      define_method(:install) do
        bin.install "switchd"
        bin.install_symlink "switchd" => "sbd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/switchboard-hub/releases/download/v0.5.0/switchd_Linux_arm64.tar.gz"
      sha256 "ee628d97757c8efa2488bdef10d6d03462b137707f1990999bae1b211edbd670"
      define_method(:install) do
        bin.install "switchd"
        bin.install_symlink "switchd" => "sbd"
      end
    end
  end

  test do
    system "#{bin}/switchd", "version"
    system "#{bin}/sbd", "version"
  end
end
