# This file was generated by GoReleaser. DO NOT EDIT.
cask "cascade" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "5e3f8ac4d59fcc011ca2b63c20f6026e45003c61ddc1c38564cac1f0f82187b6"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "98782cb27c1e74b80be6f694ad9c58df6a3204159e4331721e466c1d28216d35"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cba1f010178142c4fab1cf9dbeb311e343ec553596edb6f35d33ffc8a24c2e29"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea31198bcf76f8656c7444dabad0e55e9c8b932f5ae347cc7c09e207f08cfa2e"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_arm64.tar.gz"
    end
  end

  name "cascade"
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cascade"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cascade"]
    end
  end

  # No zap stanza required

end
