# This file was generated by GoReleaser. DO NOT EDIT.
cask "cascade" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "bbe7740232248cf7eaad29a474aef57d5c5d7718177c7b9cf74f7bea4c84edf4"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "72fc165243e0aefceca39033dc584182b11731e04502f5287dfe057cdfe5029a"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ac85648f8742766e130b3edc9863ab3c3b4dbdb5de4deee43a4564a39584a1c5"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "00745c08e3d6a250a604c245ca661ea84a40c85f447d56d69b881a41fdbb4dc4"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_arm64.tar.gz"
    end
  end

  name "cascade"
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cascade"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cascade"]
    end
  end

  # No zap stanza required

end
