# This file was generated by GoReleaser. DO NOT EDIT.
cask "cascade" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "5ab5fc70b798cd62d0376be5ecce6e9148a2487e0e8caa27a87671cb8fec7d78"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "391b8f44411a18be1ea465329af257cf71ca8bea354e4cd79cec6c482a7752cf"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2f86ba4e3b6a0ab5a370656e889febef6d759c0c07c7175c7b7b8bd584f97ce"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7d272d13c2863f767c29eb542214d346df424407cad893ec3aef1118e708ddfa"
      url "https://github.com/goliatone/cascade/releases/download/v#{version}/cascade_Linux_arm64.tar.gz"
    end
  end

  name "cascade"
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cascade"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cascade"]
    end
  end

  # No zap stanza required

end
