# This file was generated by GoReleaser. DO NOT EDIT.
cask "envset" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/envset"]
    end
  end

  version "0.10.2"

  on_macos do
    on_arm do
      sha256 "77d55536437624c496c8c0e4119ed8cd7c4dcb87be228a7f761880987520497f"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "80b8b80004ac5e730c951e0cf9cfa9e477d494ec9e4de7b48f91d7a48f9d228f"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e113206de0ae5c4321130bb4751139f869df6290b5c28e5d624012bc8db07bd6"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b505dff96716c71700aed29e49920078a4dbf81faf81e02ccc324f00b8bed536"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "envset"
  desc "run commands in an environment defined using a ini configuration file."
  homepage "https://github.com/goliatone/go-envset"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envset"

  # No zap stanza required
end
