# This file was generated by GoReleaser. DO NOT EDIT.
cask "envset" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "b00c580b846ab8a797dcb8f31ca0613325085f14dc1aaed130922cd2f4d687e7"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "219d61f57975e8e4560e06765d14f2b9094c698044d9111997e86448e1fc86c8"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3959296a7c6edf2f423e6a773b5842e615a5cf270a7a45f4e36d14400008fbac"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d8bf7095ef7b12bd672c9319b63fe77072d0639d7df6a6ee1e8f54dd7384821a"
      url "https://github.com/goliatone/go-envset/releases/download/v#{version}/envset_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envset"
  desc "run commands in an environment defined using a ini configuration file."
  homepage "https://github.com/goliatone/go-envset"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envset"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envset"]
    end
  end

  # No zap stanza required

end
