# This file was generated by GoReleaser. DO NOT EDIT.
cask "hashid" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "304bf7197728eb11e46342119c3d037381846cdc75c994233461b9f37bfe2c45"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8b3858b66cec1889e894dffd46d59448787fc2d6ca2aec44981266dac94074e6"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "30be632ef49cb7fde15d9c0a78602f254035ab39a2d6d78fe2d427b4ff4eb04d"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "20eb8fbeaf51553500048cee8fcfa1bdd56dea39231ddd72f88831f60737f57a"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Linux_arm64.tar.gz"
    end
  end

  name "hashid"
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hashid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hashid"]
    end
  end

  # No zap stanza required

end
