# This file was generated by GoReleaser. DO NOT EDIT.
cask "hashid" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/hashid"]
    end
  end

  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "cd405b55a60e3f8be918c351cd8ca3d78080325fe058b6364362357817b16cf5"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ddeca101e9b64c61d835faf1fb68f7f0fde37903df08f73f5ef85ae85e5eee1f"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "276945b8307177d007cf822102c94186836cffb8fff5150ca40f971c7d2672a6"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06b76901a1a93bcf79cae63a4b17d0a9bf725ec48f347fc6fdc8c0ba25d98fa1"
      url "https://github.com/goliatone/hashid/releases/download/v#{version}/hashid_Linux_x86_64.tar.gz"
    end
  end

  name "hashid"
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hashid"

  # No zap stanza required
end
