# This file was generated by GoReleaser. DO NOT EDIT.
cask "lgr" do
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lgr"

  on_macos do
    on_intel do
      url "https://github.com/goliatone/lgr/releases/download/v0.1.10/lgr_Darwin_x86_64.tar.gz"
      sha256 "413b5f3f0a9051857eee2ed219a6e2e86aa38f98c785945ecd25787edff96f7e"
    end
    on_arm do
      url "https://github.com/goliatone/lgr/releases/download/v0.1.10/lgr_Darwin_arm64.tar.gz"
      sha256 "5ee4ac58bd56803ed5fa1c33779f5adae69f89f2a523f47c97c03b11a20eeec0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goliatone/lgr/releases/download/v0.1.10/lgr_Linux_x86_64.tar.gz"
      sha256 "292de45647f5ddcc44aa40cbc21d6f800631d066d5ddbedfcddd8e8366dd5ad9"
    end
    on_arm do
      url "https://github.com/goliatone/lgr/releases/download/v0.1.10/lgr_Linux_arm64.tar.gz"
      sha256 "4e3effa66d202291871fbffee4083235771ceeab9c32038d4c1895070abb75ae"
    end
  end

  # No zap stanza required
end
