# This file was generated by GoReleaser. DO NOT EDIT.
cask "lgr" do
  version "0.1.15"

  on_macos do
    on_intel do
      sha256 "89bfaf3c09a2e81b9315c62f4c0c74aa1444f6966d5b96d89cd4df4a157a0d7d"
      url "https://github.com/goliatone/lgr/releases/download/v#{version}/lgr_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b04741600fde9ef344bab01db81848907f502a8d31fd41f1771f5b5d3cbc9786"
      url "https://github.com/goliatone/lgr/releases/download/v#{version}/lgr_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0900a2945b571a08d6fe9d7ffad628658dcfecdc95d485cac1c16c3de2b74b74"
      url "https://github.com/goliatone/lgr/releases/download/v#{version}/lgr_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e36a703e87ad1ff24e3e4e1d1b8715e0b82f293b48ed631fe6d343a902fd13dc"
      url "https://github.com/goliatone/lgr/releases/download/v#{version}/lgr_Linux_arm64.tar.gz"
    end
  end

  name "lgr"
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lgr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lgr"]
    end
  end

  # No zap stanza required

end
