# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchd" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "160a438fad335cd5d0c4fbd0e153b09a31b49cb6fe8446d10233b830fe19126b"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_x86_64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
    end
    on_arm do
      sha256 "0fa286bcb354471481a62e945a8a8c45634a8a8c7b07c26758631c35f21d04e8"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_arm64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f58f8199095f658625c8332226e346706011e482646da14ec1522ccbce90c37"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_x86_64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
    end
    on_arm do
      sha256 "78a49df99b0dd4f04548ce311d63ec1b8437a1d6aa9b7dd4b57bea67a3e1a7a4"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_arm64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
    end
  end

  name "switchd"
  desc "local development CLI for DNS, Caddy, and tunnel workflows on macOS."
  homepage "https://github.com/goliatone/switchboard-hub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The Homebrew cask installs the canonical `switchd` command only.
    Linux packages continue to provide the `sbd` alias.
  EOS
end
