# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchd" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_x86_64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
      sha256 "f26e45d9cc80d12771e42431c916bc871e49fcb75840a97bc7d0e9269f569154"
    end
    on_arm do
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_arm64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
      sha256 "b3d60ed11f9141834c43b68fb37eedcc91417ed9972f5d74c4229af3ce16fffe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_x86_64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
      sha256 "c5787a8736ba4268af45117edf8e1058906f9298c4e74bf2d34b2424516c77fa"
    end
    on_arm do
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_arm64.tar.gz",
        verified: "github.com/goliatone/switchboard-hub/"
      sha256 "7256fdf0da602de040de628f86a4364e42508884f09c1589fc0d3e805c424d30"
    end
  end

  name "switchd"
  desc "local development CLI for DNS, Caddy, and tunnel workflows on macOS."
  homepage "https://github.com/goliatone/switchboard-hub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/switchd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The Homebrew cask installs the canonical `switchd` command only.
    Linux packages continue to provide the `sbd` alias.
  EOS
end
