# This file was generated by GoReleaser. DO NOT EDIT.
cask "switchd" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/switchd"]
    end
  end

  version "0.8.3"

  on_macos do
    on_arm do
      sha256 "56f0b09a223cf26e2e2369a6ebe758adc3b95ba2d6d4df6daf6d0c349ffdd206"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5500b977085b28aaf7022b8d66d924db2b6dcc5870739f2f098ed50faf03d146"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "47dc3f21284a2bad662ef6acede825e50d9bf3f62a852e9c58a2745acefad037"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c63f76263d1bcce5442f73271cc8b2feee2c63475a5ab9c965c77ec29399dd8e"
      url "https://github.com/goliatone/switchboard-hub/releases/download/v#{version}/switchd_Linux_x86_64.tar.gz"
    end
  end

  name "switchd"
  desc "local development CLI for DNS, Caddy, and tunnel workflows on macOS."
  homepage "https://github.com/goliatone/switchboard-hub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "switchd"

  # No zap stanza required

  caveats <<~EOS
    The Homebrew cask installs the canonical `switchd` command only.
    Linux packages continue to provide the `sbd` alias.
  EOS
end
