# This file was generated by GoReleaser. DO NOT EDIT.
cask "webcap" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "b33355fb24fbbbe5bc68b7df40f6b8e7cf81147181cbb0032e3d1de39191ce89"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8163da2f513e95b113d462d4b4206cff4f4ad06bdcde54493a23799ccff5c18d"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1834ab22c534024e66d4302cb843369c80aedd9b07f7ce7c3f9ff2f4206f735e"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "77011ea9dbd85e42d0eef940b215b6e5d11390521bc1480d1c4b3210e9633de5"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "webcap"
  desc "Browser screenshot, image diff, workflow report, and MCP CLI."
  homepage "https://github.com/goliatone/webcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webcap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webcap"]
    end
  end

  # No zap stanza required

end
