# This file was generated by GoReleaser. DO NOT EDIT.
cask "webcap" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/webcap"]
    end
  end

  version "0.9.2"

  on_macos do
    on_arm do
      sha256 "4e22048fd99b0ac43569e6958f7bc777e5dfc02a710ed59c3c2b4946900407f1"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9e754308f245506dd9d63296cec691e986f7275a7af45a0944ac8d4411894f13"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "293e36306cb2541eef8b0000bbaff89a0285255fd1cbdb31a1353a4f1560b4dc"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fdca836a66d5c2507535c272de3466b61fa516f7a83421fab7acc72caeeb6ed8"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "webcap"
  desc "Browser screenshot, image diff, workflow report, and MCP CLI."
  homepage "https://github.com/goliatone/webcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webcap"

  # No zap stanza required
end
