# This file was generated by GoReleaser. DO NOT EDIT.
cask "webcap" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "f6a914cedb72d1aedd407091127bddaa50bd8eeb213e4eb4ce2b3bcd3dd76dcc"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea279c5fbdb91338678900995ea9c50020c9d517d8f1a70889e5fa0eeebbc696"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f54677551e7f9ef63b54d2e1fe1f01472d532ffd74ed112f17ccc2a922a40fca"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a2c114f05ac1445613509a909003f2998c717fd397953c9f9fdbe825b9cae1f"
      url "https://github.com/goliatone/webcap/releases/download/v#{version}/webcap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "webcap"
  desc "Browser screenshot, image diff, workflow report, and MCP CLI."
  homepage "https://github.com/goliatone/webcap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "webcap"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/webcap"]
    end
  end

  # No zap stanza required

end
