# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cascade < Formula
  desc "managed release cycles."
  homepage "https://github.com/goliatone/cascade"
  version "0.1.40"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.40/cascade_Darwin_x86_64.tar.gz"
      sha256 "e67e2ad60548834f65ce3e4d00c4046edc0397e263022176d5c9cf514436f135"

      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.40/cascade_Darwin_arm64.tar.gz"
      sha256 "23e34baacda8adf5c97b16c5b7cecb53894e5dd0e2c219a9ba343dab0b9f829e"

      def install
        bin.install "cascade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.40/cascade_Linux_x86_64.tar.gz"
      sha256 "5830a74110492e7745067efeb93b1e9ad37eaa6598219933045579b40875b218"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.40/cascade_Linux_armv6.tar.gz"
      sha256 "ef6700f3f10854eb906354cfb58137d96ea18f07ad907a95a3a66db3f52f5b8a"
      def install
        bin.install "cascade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/cascade/releases/download/v0.1.40/cascade_Linux_arm64.tar.gz"
      sha256 "920b6e27437cf0b75e26f7dcac2675395036d2a1a5e6fd28049e437d67b24f7c"
      def install
        bin.install "cascade"
      end
    end
  end

  test do
    system "#{bin}/cascade -version"
  end
end
