# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hashid < Formula
  desc "deterministic globally unique identifiers."
  homepage "https://github.com/goliatone/hashid"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/hashid/releases/download/v0.2.0/hashid_Darwin_x86_64.tar.gz"
      sha256 "a1d74bae6f34ca70c38d2b2abf627f708a69dadbb50caaa763dc25bb66fd5d26"

      def install
        bin.install "hashid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/hashid/releases/download/v0.2.0/hashid_Darwin_arm64.tar.gz"
      sha256 "b9007b844b5543aa6df1bca7ec56f38bcacf051d4665763687d040fbcf9481ce"

      def install
        bin.install "hashid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/hashid/releases/download/v0.2.0/hashid_Linux_x86_64.tar.gz"
      sha256 "89d1ffb667eaa20f4ea697668c54ddf73d164f8f18156354a02a2bd6d347eeaa"
      def install
        bin.install "hashid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/hashid/releases/download/v0.2.0/hashid_Linux_armv6.tar.gz"
      sha256 "ea45777ced04ea909f3a573c5718119d10642c6591d9f06f53c8bd936a89b557"
      def install
        bin.install "hashid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/hashid/releases/download/v0.2.0/hashid_Linux_arm64.tar.gz"
      sha256 "716c442ca7bc6172481a8c46f1549033a2ef553397a71e7d40aed31b9b007e5d"
      def install
        bin.install "hashid"
      end
    end
  end

  test do
    system "#{bin}/hashid -version"
  end
end
