# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgr < Formula
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.12/lgr_Darwin_x86_64.tar.gz"
      sha256 "13766da8d0fb52092aa6281de7b9e0eda119506d88544aba32253d560794ca2f"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.12/lgr_Darwin_arm64.tar.gz"
      sha256 "d78f3fc9388bf637e33f922a9c6a37ccb7135ccf850c75d5e7d434eb177f8487"

      def install
        bin.install "lgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.12/lgr_Linux_x86_64.tar.gz"
      sha256 "fdc674843c519a59dedb848f7d317f153f27174e8eea0314d3ef24044b310c8d"
      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.12/lgr_Linux_armv6.tar.gz"
      sha256 "c16105c25d330bd541da6714fc7c2b88dce9601246f0867618077660c6082962"
      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.12/lgr_Linux_arm64.tar.gz"
      sha256 "813b24056ccf5f5d16bcb669d5b0e146f7a121a97d7b05302427a36e0cf598a2"
      def install
        bin.install "lgr"
      end
    end
  end

  test do
    system "#{bin}/lgr -V"
  end
end
