# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lgr < Formula
  desc "pretty output for terminal scripts."
  homepage "https://github.com/goliatone/lgr"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.5/lgr_Darwin_x86_64.tar.gz"
      sha256 "3dd0180a38072c1f17a51d360a1a4d6b99eb174cffa18e7dc3eb5ff3d5a0e4a2"

      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.5/lgr_Darwin_arm64.tar.gz"
      sha256 "814f0155b611bc497400b1324881b93eadbf80212a4bd733a8a809e1903e46b0"

      def install
        bin.install "lgr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.5/lgr_Linux_x86_64.tar.gz"
      sha256 "183fb0e74bfc8ddec566f8402f183b7fb690ce3aac6f18ccff32fac52af210ce"
      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.5/lgr_Linux_armv6.tar.gz"
      sha256 "870c6e68894d9990d47239672f6d1acf9b41051fca114f31b4151f3b145da061"
      def install
        bin.install "lgr"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/goliatone/lgr/releases/download/v0.1.5/lgr_Linux_arm64.tar.gz"
      sha256 "790694f75d3561a897673c7cecdecc556d76a2f213e2c077b278f493b088bb9e"
      def install
        bin.install "lgr"
      end
    end
  end

  test do
    system "#{bin}/lgr -V"
  end
end
